// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSyw_8jDqHKFWUQ0LoC2plJE0XOSyGYQ',
    appId: '1:181110679638:web:592edb9ac3626d816033f7',
    messagingSenderId: '181110679638',
    projectId: 'linea2-2eab6',
    authDomain: 'linea2-2eab6.firebaseapp.com',
    storageBucket: 'linea2-2eab6.appspot.com',
    measurementId: 'G-KY513J2NJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiqdwqlEctkei0rJGzNWmaGu6DPvICok',
    appId: '1:181110679638:android:35fab6ecf53541856033f7',
    messagingSenderId: '181110679638',
    projectId: 'linea2-2eab6',
    storageBucket: 'linea2-2eab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_LAEE7N72zKKjvk5gny13moawO6Nh50',
    appId: '1:181110679638:ios:ce0b2237252acae56033f7',
    messagingSenderId: '181110679638',
    projectId: 'linea2-2eab6',
    storageBucket: 'linea2-2eab6.appspot.com',
    iosClientId: '181110679638-v5dlsni5g2u5juk4994kvg50u5oq7dna.apps.googleusercontent.com',
    iosBundleId: 'co.edu.ucundinamarca.lineaProfundizacion2',
  );
}
